# Generated by Django 5.0.4 on 2024-04-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brandDescriptionTn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='brandNameTn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brandDescription',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brandName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
