# Generated by Django 5.0.4 on 2024-04-24 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_brand_branddescriptiontn_brand_brandnametn_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='brand',
            table='Brand',
        ),
    ]
